/* ========================================================================
 * Copyright 2014 SportGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SportGroup
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package co.edu.uniandes.csw.eTours.SolicitudRetiro.logic.converter;


import co.edu.uniandes.csw.eTours.SolicitudRetiro.logic.dto.SolicitudRetiroDTO;
import co.edu.uniandes.csw.eTours.SolicitudRetiro.logic.entity.SolicitudRetiroEntity;
import java.util.ArrayList;
import java.util.List;

public class SolicitudRetiroConverter {

    /**
        id: '' /*Tipo String*
        fecha: '' /*Tipo Date*  
        idProveedor: ' ' /*Tipo String*
        estado: ' ' /*Tipo entero*  
    */
    
    public static SolicitudRetiroDTO entity2PersistenceDTO(SolicitudRetiroEntity entity) {
        if (entity != null) 
        {
            SolicitudRetiroDTO dto = new SolicitudRetiroDTO();
            dto.setId(entity.getId());
            dto.setFecha(entity.getFechaCreacion());
            dto.setEstado(entity.getEstado());
            dto.setIdProveedor(entity.getIdProveedor());
            return dto;
        } 
        else 
        {
            return null;
        }
    }

    public static SolicitudRetiroEntity persistenceDTO2Entity(SolicitudRetiroDTO dto) {
        if (dto != null) 
        {
            SolicitudRetiroEntity entity = new SolicitudRetiroEntity();
            entity.setId(dto.getId());
            entity.setIdProveedor(dto.getIdProveedor());
            entity.setFechaCreacion(dto.getFecha());
            entity.setEstado(dto.getEstado());

            return entity;
        } 
        else 
        {
            return null;
        }
    }

    public static List<SolicitudRetiroDTO> entity2PersistenceDTOList(List<SolicitudRetiroEntity> entities) {
        List<SolicitudRetiroDTO> dtos = new ArrayList<SolicitudRetiroDTO>();
        for (SolicitudRetiroEntity entity : entities) {
            dtos.add(entity2PersistenceDTO(entity));
        }
        return dtos;
    }

    public static List<SolicitudRetiroEntity> persistenceDTO2EntityList(List<SolicitudRetiroDTO> dtos) {
        List<SolicitudRetiroEntity> entities = new ArrayList<SolicitudRetiroEntity>();
        for (SolicitudRetiroDTO dto : dtos) {
            entities.add(persistenceDTO2Entity(dto));
        }
        return entities;
    }
}
