/* ========================================================================
 * Copyright 2014 SportGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SportGroup
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package co.edu.uniandes.csw.eTours.SolicitudRetiro.logic.api;

import co.edu.uniandes.csw.eTours.SolicitudRetiro.logic.dto.SolicitudRetiroDTO;
import co.edu.uniandes.csw.eTours.SolicitudRetiro.logic.dto.SolicitudRetiroPageDTO;
import java.util.List;

public interface ISolicitudRetiroLogic {

    public SolicitudRetiroDTO createSolicitudRetiro(SolicitudRetiroDTO detail);
    
    public SolicitudRetiroDTO getSolicitudRetiro(Long id);

    public void deleteSolicitudRetiro(Long id);

    public SolicitudRetiroDTO updateSolicitudRetiro(Long id, int pNuevoEstado);

    public List<SolicitudRetiroDTO> getSolicitudesRetiro();
            
    public SolicitudRetiroPageDTO getSolicitudesRetiro(Integer page, Integer maxRecords);
    
    public List<SolicitudRetiroDTO> getSolicitudesRetiroEstado(int pEstado);
    
    public SolicitudRetiroPageDTO getSolicitudesRetiroEstado( int pEstado, Integer page, Integer maxRecords);
    
    public List<SolicitudRetiroDTO> getSolicitudesRetiroFecha(String pFecha);
    
    public SolicitudRetiroPageDTO getSolicitudesRetiroFecha( String pFecha, Integer page, Integer maxRecords);
    
    public List<SolicitudRetiroDTO> getSolicitudesRetiroProveedor(Long id_Proveedor);

    public SolicitudRetiroPageDTO getSolicitudesRetiroProveedor(Long id_Proveedor, Integer page, Integer maxRecords);

    
}
